spring:
  data:
    redis:
      host: 47.99.113.58
      password: asd1245+asd
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asd1245+asd
    url: jdbc:mysql://47.99.113.58:3306/mini_chat?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  cloud:
    alicloud:
      oss:
        sts:
          access-key: LTAI5tRjYr5f8FecYJuFzP8S
          secret-key: lhtPoOnsm1ZFnsuNxSSoYbTWCZOInY
        endpoint: oss-cn-beijing.aliyuncs.com
  servlet:
    multipart:
      enabled: true